### PR TITLE
#162 phone number unique

### LINKED ISSUE #162: BUG-162: Mobile phone number should be a unique identifier when a user signs up
### Related Issue(s): 
#47

### Relevant File(s):
SignUpPageActivity.java.
Not a relevant file, but constraints should be added to the Firestore Database.

### Describe the bug:
User should sign up with one phone number which uniquely belongs to that user. 
At the moment, the phone number in the database aren't unique.

### To Reproduce:
1. Sign up a new account using phone number X
2. Sign up a new account again using phone number X
3. Both registration should be possible

### Expected behavior
When creating an account with a phone number, this phone number should be unique for the account and should not be used for an another account.

### Screenshots/Video:
Screenshot from 2021-01-21 21-33-34

Screenshot from 2021-01-21 21-33-10

### PR DESCRIPTION
**Pull request by ShawnGuerra-Bautista**
### Related Issues
#162 

### Description
When a user registers, the system checks whether the phone number exists within the system. If it does, then it will not let the user register. Otherwise, the user will be registered. For editing a phone number, the new phone number must not be associated to another account, or else the editing of a phone number will fail.

~~NOTE: #189 is responsible to make sure that phone numbers are registered in a certain format. And, in https://github.com/Landry333/Big-Owl/pull/218, when a user enter a phone number to register, the CreateUser method will take in the formatted phone number. **Therefore, when #218 is merged to staging, my code will be able to make sure that it will detect duplicate phone numbers regardless of how the user writes them**. So, please ignore the format of the phone number.~~

### How to check PR
- Try to register or editing an account with a phone number already associated with an existing account
- Examples: +16918396024, +19876543210, +19612727197, or +12448297770.
- The system should reject the registration of account containing these numbers
~~- NOTE: Again, #189 is responsible on the formatting of those numbers, and is addressed in PR #218. Therefore, the system will detect duplicates **regardless of the format** (e.g. +1-691-839-6024) after #218 has been merged.~~

### CODE REVIEW

File: app/src/main/java/com/example/bigowlapp/repository/UserRepository.java [hunk 1]
```diff
@@ -1,11 +1,39 @@
...
 
     // TODO: Dependency Injection Implementation for Firestore
     public UserRepository() {
         super("users");
     }
+
+    public Task<Void> isPhoneNumberInDatabase(String phoneNumber) {
+        Task<QuerySnapshot> taskGetPhoneNumber =
+                collectionReference.whereEqualTo("phoneNumber", phoneNumber)
+                        .limit(1)
```
Comment (refatK) [inline app/src/main/java/com/example/bigowlapp/repository/UserRepository.java:19]: good use of limit to make the db call more efficient

File: app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java [hunk 2]
```diff
@@ -0,0 +1,14 @@
+package com.example.bigowlapp.repository.exception;
+
+public class PhoneNumberTakenException extends Exception {
```
Comment (refatK) [inline app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java:3]: This is great for debugging and for letting us send an appropriate error message in the UI.

File: app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+
+    private static final String DEFAULT_MESSAGE = "Phone Number is already in the database.";
```
Comment (refatK) [inline app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java]: You should change the message to not mention "database", since this message is seen by a user, and the database has no relevance to them.

The message should simply tell the user that the phone number is already in use, is taken, or that an account is already registered with the number. Anything along those lines

File: app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java [hunk 4]
```diff
@@ -18,32 +19,68 @@ public SignUpViewModel() {
...
+
         // add user email and password to authentication database
-        Task<AuthResult> taskAuthSignUpResult = repositoryFacade.getAuthRepository().signUpUser(email, password);
+        Task<AuthResult> taskAuthSignUpResult = taskIsPhoneNumberInDatabase.continueWithTask(task -> {
+            if (task.isSuccessful()) {
+                return signUpUserInAuthRepo(email, password);
+            } else {
+                throw task.getException();
+            }
+        });
```
Comment (refatK) [inline app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java:33]: this can be condensed to...

```java
Task<AuthResult> taskAuthSignUpResult = taskIsPhoneNumberInDatabase.onSuccessTask(task -> {
                return signUpUserInAuthRepo(email, password);
        });
```

Although this is minor and nothing too important, so you can ignore this if you want.
Applies to all other cases where the `continueWithTask` simply throws the exception of the previous task when `task.isSuccessful()` is false.

File: app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java [hunk 5]
```diff
@@ -18,32 +19,68 @@ public SignUpViewModel() {
...
-                User user = new User();
-                String uid = getCurrentUserUid();
-                user.setUid(uid);
-                user.setEmail(email);
-                user.setPhoneNumber(phoneNumber);
-                user.setFirstName(firstName);
-                user.setLastName(lastName);
-                repositoryFacade.getUserRepository().addDocument(uid, user);
-                return Tasks.forResult(null);
+                return createUserEntry(email, phoneNumber, firstName, lastName);
```
Comment (refatK) [inline app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java:38]: Looks cleaner, nice!

File: app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java [hunk 6]
```diff
@@ -54,8 +91,18 @@ public String randomNumberStringGenerator() {
...
 
+    public boolean isPhoneNumberUnique(String phoneNumber) {
+        LiveDataWithStatus<User> liveDataWithStatus =
+                repositoryFacade.getUserRepository()
+                        .getDocumentByAttribute("phoneNumber", phoneNumber, User.class);
+
+        return liveDataWithStatus.getValue() != null
+                || liveDataWithStatus.getValue().getPhoneNumber() != null;
+
+    }
```
Comment (refatK) [inline app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java]: This is unused. Seems like removeable dead code.

**Review by refatK — CHANGES_REQUESTED** [review]
Tested the feature and worked as expected. When I registered with a number already in use I got a toast message telling so. Registering with an unused number let me register as expected.

I requested some minor changes, bit other than that, the feature is good.

File: app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java (hunk 4 above)
Comment (ShawnGuerra-Bautista) [reply app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java:33]: The reason I'm doing it this way is to throw an exception just in case the task fails, and to halt the operation.
I don't want anything else to run after that task. 

Does onSuccessTask do that?

File: app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java (hunk 3 above)
Comment (ShawnGuerra-Bautista) [reply app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java:5]: Yeah, I'll change that

Comment (ShawnGuerra-Bautista) [reply app/src/main/java/com/example/bigowlapp/repository/exception/PhoneNumberTakenException.java]: Yeah, that's reasonable.

File: app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java (hunk 4 above)
Comment (refatK) [reply app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java:33]: yep:
https://developers.google.com/android/reference/com/google/android/gms/tasks/Task#onSuccessTask(com.google.android.gms.tasks.SuccessContinuation%3CTResult,%20TContinuationResult%3E)

but if you perfer just to leave it as is, that's fine too.

Comment (ShawnGuerra-Bautista) [reply app/src/main/java/com/example/bigowlapp/viewModel/SignUpViewModel.java:33]: Oh, that's pretty cool.

However, the only problem I have with it is that it doesn't mention it will throw an exception implicitly; it will simply cancel the task without any indication. I believe that for every task, there should be some exception handling.

**Review by refatK — APPROVED** [review]
Tested the addition of unique phonenumber for  edit profile, and it works now.

Thanks for also addressing my review comments.

**Review by KhangZhengNg — APPROVED** [review]
Overall, good job on refactoring & adding more exceptions for profile editing and account creation
