### PR TITLE
#183 Schedule not accesible when added using the Schedule Form

### LINKED ISSUE #183: BUG-183: Schedule not accesible when added using the Schedule Form
### Related Issue(s): 
#30, #31

### Relevant File(s):
- [ScheduleRepository.java](https://github.com/Landry333/Big-Owl/blob/78f91eee58562adc5da5e2bdee74404fd68b4236/app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java)
- [Schedule.java](https://github.com/Landry333/Big-Owl/blob/78f91eee58562adc5da5e2bdee74404fd68b4236/app/src/main/java/com/example/bigowlapp/model/Schedule.java)
- [ListOfScheduleActivity.java](https://github.com/Landry333/Big-Owl/blob/78f91eee58562adc5da5e2bdee74404fd68b4236/app/src/main/java/com/example/bigowlapp/activity/ListOfScheduleActivity.java)

### Describe the bug:
When checking the schedules of  group you are a part of , they don't show up in the Schedules list page even though they are stored in the database.

### To Reproduce:
1. As a user who has group members create a schedule for you members.
2. Login as a second user who is a part of the group where you just added schedules for the users
3. Click on "Supervised Group"
4. Click on the group where you added the schedule with the first user
5. Click on Schedules
6. You'll either get a no schedules found warning or a list of schedules missing the one that should have been added

### Expected behavior
The schedule should be in the schedule list.

### Additional context: <optional>
It seems there is an issue of naming differences between the Schedule model attributes and the query to the database in the ScheduleRepository.

### PR DESCRIPTION
**Pull request by refatK**
### Related Issues
Closes #183 

### Description
I fixed the bug in which schedules were not showing up in the list that allows us to accept or reject them

### How to check PR
1. Login as a user with group members
2. Set a schedule for one or more of the group members using set schedule
3. Logout and now login as a user you just added a schedule for
4. Click on "Supervised Group"
5. Click on the group where you added the schedule with the first user
6. Click on Schedule

The schedule should be in the schedule list.

### CODE REVIEW

**Review by Landry333 — APPROVED** [review]
The bug was easily fixed. I tested the feature and it works well. I approve

**Comment by refatK** [comment]
I'm also adding a test while I'm at it

File: app/src/main/java/com/example/bigowlapp/viewModel/ScheduleViewRespondViewModel.java [hunk 1]
```diff
@@ -74,7 +76,26 @@ public void notifySupervisorScheduleResponse() {
     }
 
     public boolean isOneMinuteAfterLastResponse() {
-        long userLastResponseTime = getUserScheduleResponse().getResponseTime().toDate().getTime();
+        Timestamp responseTimestamp = getUserScheduleResponse().getResponseTime();
+
+        // If there was no response yet, than we should allow response to go through
```
Comment (ShawnGuerra-Bautista) [inline app/src/main/java/com/example/bigowlapp/viewModel/ScheduleViewRespondViewModel.java]: Petty comment, but "then" should be used rather than "than".

File: app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java [hunk 2]
```diff
@@ -27,7 +27,7 @@ public ScheduleRepository() {
     public MutableLiveData<List<Schedule>> getListSchedulesFromGroupForUser(String groupID, String userID) {
         MutableLiveData<List<Schedule>> listOfTData = new MutableLiveData<>();
         collectionReference.whereEqualTo("groupUId", groupID)
-                .whereArrayContains("membersList", userID)
+                .whereArrayContains("memberList", userID)
```
Comment (ShawnGuerra-Bautista) [inline app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java:30]: Nice catch.

**Review by ShawnGuerra-Bautista — APPROVED** [review]
Code wise, it's very good. Bug is fixed and the app is working as intended.

The only thing that I found is a very small and insignificant typo in your comments.

To be fair, you can change it if you want, otherwise it's all good.
