### PR TITLE
#202 Fixed Missing Notifications

### LINKED ISSUE #202: BUG-202: Schedule Response is not seen in Notification List
### Related Issue(s): 
#37, #52

### Relevant File(s):
- ScheduleViewRespondViewModel.java
- ScheduleRequest.java
- NotificationRepository.java

### Describe the bug:
When notifications are added to the database for accepting/rejecting schedule  requests, they don't seem to show up correctly when getting all notification from the NotificationRepository

### To Reproduce:
1. Go to Hompage
2. Click on notification bell icon and see the notifications

### Expected behavior
The notification shows up, but it's not formatted in the expected matter.

### Additional context: <optional>
This seems to have to do with an issue in types when the notifications are created. The type should follow the Constant when created in ScheduleViewRespondViewModel.

### PR DESCRIPTION
**Pull request by refatK**
### Related Issues
Closes #202 

### Extra Note
I actually made an improvement to the way Notification are set so that when we code new Notifications which can be seen in this commit (https://github.com/Landry333/Big-Owl/commit/dd56126498aa4275459570384db574e6be0367ee). This is because there is less stuff for us to maintain and worry about But it would effect the type field of the Notifications (which would make the current Notifs in our db invalid), and it would require a slight amount of changes to the code for Notification page (although it should be relatively simple)

### Description
I fixed the bug where the ScheduleRequests would not show up in the notification list and made some changes to prevent us from causing that to happen again

### How to check PR
- Create a Schedule for a user (ex: send a schedule to TestUser2 using TestUser1)
- Login as the User you sent a Schedule to (ex: TestUser2) and accept or reject this schedule
- Find the notification created as a result of accepting/rejecting a schedule and the type field should match the Constant here (https://github.com/Landry333/Big-Owl/blob/1c8f8cdea55677d6fcd4b04414f0914bf814b58e/app/src/main/java/com/example/bigowlapp/model/Notification.java#L12)

### CODE REVIEW

File: app/src/main/java/com/example/bigowlapp/model/Notification.java [hunk 1]
```diff
@@ -6,34 +6,37 @@
...
-    }
-
-    public String getType() {
+    public Type getType() {
         return type;
     }
 
-    public void setType(String type) {
+    // This private setter is necessary for Firebase data to model mapping
+    private void setType(Type type) {
```
Comment (ShawnGuerra-Bautista) [inline app/src/main/java/com/example/bigowlapp/model/Notification.java:39]: Why make this private?
Wouldn't it be better to just leave it as public as probably other classes may need it?

Also, this is considered a code smell by Sonarqube.

File: app/src/main/java/com/example/bigowlapp/model/Notification.java [hunk 2]
```diff
@@ -6,34 +6,37 @@
...
+        SCHEDULE_REQUEST(ScheduleRequest.class);
+
+        public final Class<? extends Notification> typeClass;
+
+        Type(Class<? extends Notification> typeClass) {
+            this.typeClass = typeClass;
+        }
+    }
+
+    private Type type;
```
Comment (ShawnGuerra-Bautista) [inline app/src/main/java/com/example/bigowlapp/model/Notification.java:21]: Nice implementation!

File: app/src/main/java/com/example/bigowlapp/repository/NotificationRepository.java [hunk 3]
```diff
@@ -24,17 +19,11 @@ public NotificationRepository() {
...
-    public NotificationRepository(FirebaseFirestore mFirebaseFirestore, CollectionReference collectionReference) {
-        super(mFirebaseFirestore, collectionReference);
-    }
-
     public MutableLiveData<List<SupervisionRequest>> getListOfSupervisionRequestByAttribute(String attribute, String attrValue,
                                                                                             Class<? extends SupervisionRequest> tClass) {
         MutableLiveData<List<SupervisionRequest>> listOfTData = new MutableLiveData<>();
         collectionReference.whereEqualTo(attribute, attrValue)
-                .whereEqualTo("type", Constants.SUPERVISION_TYPE)
+                .whereEqualTo("type", Notification.Type.SUPERVISION_REQUEST)
```
Comment (ShawnGuerra-Bautista) [inline app/src/main/java/com/example/bigowlapp/repository/NotificationRepository.java]: Consider removing this "magic literal" and refactor the code; string "type" should be kept in a variable.

File: app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java [hunk 4]
```diff
@@ -18,7 +18,7 @@ public ScheduleRepository() {
     }
 
     public Task<Void> updateScheduleMemberResponse(String scheduleId, String userUid, UserScheduleResponse currentUserScheduleResponse) {
-        return collectionReference.document(scheduleId).update("members.".concat(userUid), currentUserScheduleResponse);
+        return collectionReference.document(scheduleId).update("userScheduleResponseMap.".concat(userUid), currentUserScheduleResponse);
```
Comment (ShawnGuerra-Bautista) [inline app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java]: Again, consider removing this magic literal.

**Review by ShawnGuerra-Bautista — CHANGES_REQUESTED** [review]
Code is much more clean; good job.

Although, there are some changes I request.

File: app/src/main/java/com/example/bigowlapp/model/Notification.java (hunk 1 above)
Comment (refatK) [reply app/src/main/java/com/example/bigowlapp/model/Notification.java:39]: I made it private to prevent the issue that caused the bug in  the first place, the setter being used to change the notifs type.

Ideally I would have simply removed the setter to fit the OOP principle that the type should be read only, but the setter is needed for Firebase model mapping.

Making it private allows firebase mapping to work, while also enforcing the read only nature of this property

File: app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java (hunk 4 above)
Comment (refatK) [reply app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java]: Totally agree, but will leave this for #82 .

Although if you think it's better to use a constant now, just reply that I should do so.

Applies to above comment too

Comment (ShawnGuerra-Bautista) [reply app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java]: Do it anyways.
Just make sure you're commit comment is in this format "[#202] Refactor: Removed Magic Literal; *additional comment*"

Comment (refatK) [reply app/src/main/java/com/example/bigowlapp/repository/ScheduleRepository.java]: @ShawnGuerra-Bautista Done!

**Review by KhangZhengNg — APPROVED** [review]
Overall, nice work on creating the enum Type in Notification model and nice code cleaning after the refactoring.

File: app/src/main/java/com/example/bigowlapp/model/Notification.java (hunk 1 above)
Comment (ShawnGuerra-Bautista) [reply app/src/main/java/com/example/bigowlapp/model/Notification.java:39]: Alright.

Since it's the cause of the bug, I understand why it should be private.

**Review by ShawnGuerra-Bautista — APPROVED** [review]
